# read: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: CSS Transform
        run: |
          sh <(curl https://yandeu.github.io/css-transform/sh.sh) css/style.css bundle.css
          cat bundle.css
